#include <tweakval.h>
#include <gamefontgl.h>

#include <BeneathGame.h>

BeneathGame::BeneathGame() :
	m_isInit( false )
{
}

// fixed update, for gameplay stuff
void BeneathGame::updateSim( float dt )
{
	printf("UpdateSim %3.2f\n", dt );
}

// "as fast as possible" update for effects and stuff
void BeneathGame::update( float dt )
{
	printf("Update %3.2f\n", dt );
}

void BeneathGame::init()
{
	// Load the font image
	ILuint ilFontId;
	ilGenImages( 1, &ilFontId );
	ilBindImage( ilFontId );		
	
	if (!ilLoadImage( (ILstring)"gamedata/andelemo.png" )) {
		printf("Loading font image failed\n");
	}
	
	// Make a GL texture for it
	m_glFontTexId = ilutGLBindTexImage();
	m_fntFontId = gfCreateFont( m_glFontTexId );

	// A .finfo file contains the metrics for a font. These
	// are generated by the Fontpack utility.
	gfLoadFontMetrics( m_fntFontId, "gamedata/andelemo.finfo");

	printf("font has %d chars\n", 
		gfGetFontMetric( m_fntFontId, GF_FONT_NUMCHARS ) );					

}
	
void BeneathGame::redraw()
{
	glClearColor( _TV( 0.1f ), _TV(0.2f), _TV( 0.4f ), 1.0 );
	glClear( GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT );

	if (!m_isInit)
	{
		m_isInit = true;
		init();
	}
	glMatrixMode( GL_PROJECTION );
	glLoadIdentity();

	gluOrtho2D( 0, 800, 0, 600 ) ;

	glMatrixMode( GL_MODELVIEW );
	glLoadIdentity();

	// Title text
	gfEnableFont( m_fntFontId, 32 );	
	gfBeginText();
	glTranslated( _TV(260), _TV(500), 0 );
	gfDrawString( "The World Beneath" );
	gfEndText();

	// Bottom text
	gfEnableFont( m_fntFontId, 20 );	
	gfBeginText();
	glTranslated( _TV(180), _TV(10), 0 );
	gfDrawString( "LudumDare 15 - Joel Davis (joeld42@yahoo.com)" );
	gfEndText();
}