# sconsfile for linux/mac
# this is untested, will probably take some modifications to actually work

env = Environment()

env.AppendUnique( CPPPATH=[ ".", "/path/to/allegro-4.2.2/include"],
                  LIBPATH=[ "/path/to/allegro-4.2.2/lib/unix" ],
                  CPPDEFINES=['-DNDEBUG'],
                  
                  # release build
                  #LIBS = ['alleg', 'alleg_unsharable', 'X11', 'Xm', 'Xext', 'Xcursor', 'pthread' ],
                  )
                  
                  # debug build
                  #LIBS = ['alleg', 'alld_unsharable', 'X11', 'Xm', 'Xext', 'Xcursor', 'pthread' ] )
                  #CXXFLAGS = ['-g'] )

SOURCES = ['wander_main.cpp', 'tilemap.cpp', 'pixbot.cpp', 'game_obj.cpp' ]
env.Program( 'wander', SOURCES )
